sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - $HOME/travisCacheDir
env:
  global:
    - secure: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4GIgqXdPOkehPwITfExrH+NrT\nq3uJlNS0ZWeEd/QCVLayVGTScAzYrJZcC3hw09rHe9fQv0VRtvfGN1O4Zh4Q1cTI\n1DBswD5F68SFxWN/DbPafCmu+wuCEr767iCqw8JwxynChyRYMOcdf22VQz8QUbfb\nCKwHayMOtCC8XiPLBQIDAQAB"
    - coverity_branch: dev

addons:
  coverity_scan:
    project:
      name: "lysevi/dariadb"
      description: "Build submitted via Travis CI"
    build_command_prepend: ""
    build_command: "bash .travis/build.sh"
    branch_pattern: $coverity_branch
    notification_email: lysevi@gmail.com
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev  
      - libboost-filesystem-dev 
      - libboost-test-dev 
      - libboost-program-options-dev 
      - libasio-dev 
      - libboost-log-dev 
      - libboost-regex-dev 
      - libboost-date-time-dev
      - cmake  
      - g++-6  
      - gcc-6 
      - cpp-6
      - clang
      
before_install:
   - pip install --user cpp-coveralls
   - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
   - tar xf lcov_1.11.orig.tar.gz
   - sudo make -C lcov-1.11/ install
   - gem install coveralls-lcov
   - gem install travis
   - cmake --version
   - cd ${TRAVIS_BUILD_DIR}
   - git submodule init
   - git submodule update

matrix:
  include:
    - os: linux
      compiler: gcc-6
      env: GCOV=FALSE CLANG=FALSE
#    - os: linux
#      compiler: gcc-6
#      env: GCOV=TRUE CLANG=FALSE
#    - os: linux
#      compiler: clang
#      env: CLANG_SANITIZER=ASAN_UBSAN CLANG=TRUE GCOV=FALSE
#    - os: linux
#      compiler: clang
#      env: CLANG_SANITIZER=TSAN CLANG=TRUE GCOV=FALSE
#    - os: linux
#      compiler: clang 
#      env: CLANG=TRUE GCOV=FALSE

script: 
   - travis encrypt --no-interactive COVERITY_SCAN_TOKEN=KgdhLtxiiaMHA19InT-uIA
   - bash .travis/build.sh
